name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # --- BLOCO DE DEBUG (NOVO) ---
    - name: Debug - Listar arquivos
      run: |
        echo "Mostrando arquivos na raiz:"
        ls -la
        echo "Mostrando arquivos em currency-report:"
        ls -la currency-report/
        echo "Mostrando arquivos em currency-history:"
        ls -la currency-history/
    # -----------------------------

    - name: Test Service A (Report)
      working-directory: ./currency-report
      run: |
        pip install -r requirements.txt
        # O -vv mostra detalhes m√°ximos
        pytest -vv

    - name: Test Service B (History)
      working-directory: ./currency-history
      run: |
        pip install -r requirements.txt
        pytest -vv

    - name: Build Docker Images
      run: |
        docker build -t currency-report ./currency-report
        docker build -t currency-history ./currency-history